#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PREZTO_SETTINGS=${ZDOTDIR:-$HOME}/.zprezto/settings/

if [ -d "$PREZTO_SETTINGS" ]; then
  if [ "$(ls -A $PREZTO_SETTINGS)" ]; then
    for config_file ($PREZTO_SETTINGS*.zsh) source $config_file
  fi
fi
